#!/usr/bin/env python
"""
A little *nix shell written in python.
"""
import cmd, os, sys, shlex

sh = cmd.Cmd()

# delegate to user's main shell (bash or whatever):
sh.default = lambda cmd  : os.system(cmd)

# add 'cd' command since python won't change directories
# when the child process does:
sh.do_cd = lambda path : os.chdir(path)

# allow extending the command list at runtime:
def do_def(line):
    """
    define a new command.
    ex:
    > def sum sum([ int(x) for x in arg.split() ])
    > sum 1 2 3 4 5
    """
    head, *tail = shlex.split(line, 1)
    tail = ' '.join(tail)
    code = 'lambda arg: print(eval(%r))' % tail
    func = eval(code)
    setattr(sh, "do_%s" % head, func)

sh.do_def = do_def ; del do_def

go = lambda : sh.cmdloop()
go()

